version: '3'

networks:
  db-link:
    driver: bridge

services:
  mongodb-primary:
    container_name: mongodb-primary
    image: bitnami/mongodb
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - ./mongodb:/bitnami/mongodb
    networks:
      - db-link

  emqx:
    container_name: emqx
    image: emqx/emqx
    env_file: .env
    ports:
      - "18083:18083"
      - "1883:1883"
      - "8083:8083"
    environment:
      - EMQX_NODE__COOKIE=emqx
    volumes:  
      - "./emqx/data:/opt/emqx/data"
      - "./emqx/etc:/opt/emqx/etc"
      - "./emqx/log:/opt/emqx/log"

  nuxt:
    container_name: nuxt
    image: becemgharbi/esp-admin
    env_file: .env
    depends_on:
      - mongodb-primary
      - emqx
    ports:
      - "3000:3000"
    networks:
      - db-link
    environment:
      - DATABASE_URL=mongodb://root:${MONGODB_ROOT_PASSWORD}@mongodb-primary/esp-admin?authSource=admin&retryWrites=true&w=majority